### ISSUE TITLE
Errors when running without `MINIO_INSECURE`

### ISSUE THREAD

**Issue by rjhenry** [hkdobrev/minio-deploy-action#2]
Running this action without `MINIO_INSECURE` set causes the following issue:
```
+ insecure_option=
+ [[ false == \t\r\u\e ]]
+ mc alias set '' deploy https://minio.hns.assureddt.uk/ *** ***
mc: <ERROR> Incorrect number of arguments for alias set command. Invalid arguments provided, please refer `mc <command> -h` for relevant documentation.
```

Naturally, this causes some problems running this in production!

For now, we're working around this by setting the env var to `true` to allow the use of the insecure flag, but as this doesn't validate TLS certificates it's not an ideal situation.

As a proposed fix, I think simply unquoting the call to `$insecure_option` should do the trick, as then an empty string wouldn't be parsed as an additional argument. It's not ideal, but should do the trick!

**Comment by KlausPopp** [comment]
Suggestion: Install a fixed version of mc from https://dl.min.io/client/mc/release/linux-amd64/archive/

**Comment by hkdobrev** [comment]
@rjhenry @KlausPopp Thanks for reporting and I'm sorry for the inconvenience!

Could you please re-check again?

**Comment by hkdobrev** [comment]
Fixed in https://github.com/hkdobrev/minio-deploy-action/commit/98438a5d45068824d87fc8938095ae86dabc05bd

**Comment by hkdobrev** [comment]
@rjhenry I've also added `v1.1` moving tag for the action if you'd like to be on a more stable version and not be disrupted by new features on the `v1` release line.
